 # Tensorflow fundamental
 * Introduction to tensors
 * Getting informations from tensors
 * Manipulation of tensors
 * Tensors and numpy
 * using @tf.functions to speedup the python functions
 * Using GPU with TensorFlow (or TPUs)

## Introduction to tensors

In [96]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.15.0


In [97]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [98]:
scalar.ndim

0

In [99]:
# create a vector
vector = tf.constant([1,1])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [100]:
vector.ndim

1

In [101]:
# create a matrix
matrix = tf.constant([[1,1,2],[2,2,3],[3,3,4]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 2],
       [2, 2, 3],
       [3, 3, 4]], dtype=int32)>

In [102]:
matrix.ndim

2

In [103]:
another_matrix = tf.constant([[10.,7.],[1.,3.]], dtype=tf.float16)

In [104]:
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 1.,  3.]], dtype=float16)>

In [105]:
another_matrix.ndim

2

In [106]:
tensor = tf.constant(
    [
        [[1,2,3],[4,5,6]],
        [[7,8,9],[10,11,12]],
        [[13,14,15],[16,17,18]]
    ]
)

In [107]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [108]:
tensor.ndim

3

## Creating tensors with `tf.variable`

In [109]:
# create a same tensor as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [110]:
# # lets try to change elements in the changable_tensor
# changable_tensor[0]=7

In [111]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [112]:
# unchangable_tensor[0].assign(7)
# unchangable_tensor

## Create random tensors
* random tensor which have arbitary size and numbers

In [113]:
rand1 = tf.random.Generator.from_seed(42)
rand1 = rand1.normal(shape=(3,2))
rand1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [114]:
rand2 = tf.random.Generator.from_seed(42)
rand2 = rand2.normal(shape=(3,2))
rand2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [115]:
(rand1 == rand2)

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffle the order of tensors

In [116]:
# shuffle a tensor (valuable when we want the data to be shuffled so the inherent order doesnt effect the learning)
not_shuffled = tf.constant([[10,7],[3,4],[2,10]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2, 10]], dtype=int32)>

In [117]:
tf.random.set_seed(0)
shuffled = tf.random.shuffle(not_shuffled,seed=0)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2, 10]], dtype=int32)>

In [118]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [119]:
tf.zeros(shape=[10,4])

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy array into tensors

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on GPU (much faster for numerical computations)

In [120]:
npA = np.arange(1,25,dtype=np.int32)
npA
A = tf.constant(npA,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting information from Tensors:

When dealing with tensors we probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or Dimension
* Size



In [121]:
# create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [122]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [123]:
# Get various attributes of the tensor
print("Data type of tensor : ",rank_4_tensor.dtype)
print("Number of dimensions : ",rank_4_tensor.ndim)
print("Shape of tensor : ",rank_4_tensor.shape)
print("Element along the 0 axis : ",rank_4_tensor.shape[0])
print("Element along the last axis : ",rank_4_tensor.shape[:-1])
print("Total no of elements in the tensor : ",tf.size(rank_4_tensor).numpy())

Data type of tensor :  <dtype: 'float32'>
Number of dimensions :  4
Shape of tensor :  (2, 3, 4, 5)
Element along the 0 axis :  2
Element along the last axis :  (2, 3, 4)
Total no of elements in the tensor :  120


## Indexing Tensors
Tensors can be indexed like python lists

In [124]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [125]:
# Get the first element from each dimesion from each index except the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [126]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [127]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [128]:
# create a rank 2 tensor
rank_2_tensor = tf.constant([[1,2],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [129]:
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [130]:
some_list = [1,2,3,4]
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [131]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [132]:
# Turning the rank_2_tensor into rank_3_tensor
# Adding a extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [133]:
# alternative method expand axis at the end of the tensor
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [134]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## Manipulating the Tensors
**Basic Operations** `+`,`-`,`*`,`/`

In [135]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**Matrix Multiplication**

Two rules for matrix multiplication that is to be satisfied are :

1. Inner dimensions must match
2. The resulting matrix has the same shape of the inner dimensions


In [136]:
I2 = tf.constant([[1,0],[0,1]])
t1 = tf.constant([[1,-1],[-1,1]])
t2 = tf.constant([[1,-1],[-1,1]])
tf.linalg.matmul(t1,I2) == t1

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [137]:
print(tensor)
print(tensor * tensor)
print(tf.linalg.matmul(tensor,tensor))

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  49]
 [  9  16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [138]:
# matrix multiplcation with python operator '@'
tensor @ tensor == tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [139]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [140]:
X @ tf.reshape(y,shape=(2,3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [141]:
tf.transpose(X) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## The Dot Product
Matrix multiplication is also referred to as the dot product

You can perform matrix multiplication using :

* `tf.matmul()`
* `tf.tensordot()`

In [142]:
X,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [143]:
# perform the dot product on X and Y (requires necessary transposition)
tf.transpose(X), tf.transpose(y)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [144]:
tf.tensordot(tf.transpose(X),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [145]:
# perfrom matrix multiplication between X, y(reshaped)
tf.matmul(X,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [146]:
tf.matmul(X,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [147]:
print("normal y : "),print(y,'\n')
print("reshaped y : "),print(tf.reshape(y,(2,3)),'\n')
print("y transposed : "),print(tf.transpose(y),'\n')

normal y : 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

reshaped y : 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

y transposed : 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



(None, None)

## Changing the datatype of a tensor


In [148]:
tf.__version__

'2.15.0'

In [149]:
# create a tensor with default datatype
B = tf.constant([1.4,2.34])
B.dtype

tf.float32

In [150]:
C = tf.constant([1,2])
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 tf.int32)

In [151]:
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.4 , 2.34], dtype=float16)>,
 tf.float16)

In [152]:
E = tf.cast(C, dtype=tf.int16)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 2], dtype=int16)>,
 tf.int16)

## Aggregating tensors

Basically it implies condesing them from multiple values down to smaller amount of values

In [153]:
# Get the absoulute values
D = tf.constant([-7,10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [154]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [155]:
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

Following forms of aggregations :

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [156]:
# create a random big tensor
E = tf.constant(np.random.randint(0,100,50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([77, 14, 50,  1,  0, 83, 16, 89, 70,  4, 69,  0, 72, 30, 23, 90, 95,
       58, 20, 44,  4, 62, 33, 28,  5, 52, 96, 96, 95,  4, 27, 25, 93, 97,
        3, 65, 40, 78, 80, 92, 51, 40, 80, 50, 36, 36, 37, 63, 94, 47])>

In [157]:
tf.size(E), E.ndim, E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [158]:
# find the minimum of the tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [159]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [160]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [161]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2514>

In [162]:
import tensorflow_probability as tfp

In [163]:
# find the variance of the tensor
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1012>

In [164]:
# find the standard deviation of the tensor
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.814487>

## Find the positional maximum and minimum

In [165]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [166]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [167]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## Squeezing a tensor (remove all single dimensions)

In [171]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform([50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [175]:
gs = G_squeezed = tf.squeeze(G)
gs, gs.shape, gs.ndim

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]),
 1)

## One-hot encoding tensors

In [179]:
# create a list of indices
rand_list = [0,1,2,3] # red, green, blue, yellow

In [180]:
# one hot encode our list of indices
tf.one_hot(rand_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [183]:
# specify custom values for one hot encoding
tf.one_hot(rand_list, depth=4, on_value=" hmm ", off_value=" haha ")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b' hmm ', b' haha ', b' haha ', b' haha '],
       [b' haha ', b' hmm ', b' haha ', b' haha '],
       [b' haha ', b' haha ', b' hmm ', b' haha '],
       [b' haha ', b' haha ', b' haha ', b' hmm ']], dtype=object)>

## Some math functions

In [188]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [193]:
tf.square(H), tf.sqrt(tf.cast(H,dtype=tf.float16)), tf.math.log(tf.cast(H,dtype=tf.float16))

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
       dtype=float16)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
        2.197 ], dtype=float16)>)

## Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

In [196]:
# create a tensor directly from numpy arrays

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [198]:
# converting back tensor to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [200]:
# the default datatypes are slightly different
numpy_J = tf.constant(np.array([3.,4.,5.]))
tensor_J = tf.constant([3.,4.,5.,])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPU's

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("TPU")

/bin/bash: line 1: nvidia-smi: command not found
